export const routes = {
  home: '/',
  admin: {
    dashboard: '/dashboard/admin',
    categories: '/dashboard/admin/categories',
    newCategory: '/dashboard/admin/categories/new',
    newSubCategory: '/dashboard/admin/sub-categories/new',
    categoryDetail: (id: string) => `/dashboard/admin/categories/${id}`,
    categoryEdit: (id: string) => `/dashboard/admin/categories/${id}/edit`,
    stores: '/dashboard/admin/stores',
    orders: '/dashboard/admin/orders',
    subCategories: '/dashboard/admin/sub-categories',
    subCategoryDetail: (id: string) => `/dashboard/admin/sub-categories/${id}`,
    subCategoryEdit: (id: string) => `/dashboard/admin/sub-categories/${id}/edit`,
    offerTags: '/dashboard/admin/offer-tags',
    coupons: '/dashboard/admin/coupons',
    seller: '/admin/dashboard/seller',
    products: '/admin/dashboard/products',
    customers: '/admin/customers',
    settings: '/admin/settings',
  },
  seller: {
    dashboard: '/dashboard/seller',
    stores: '/dashboard/seller/stores',
    newStore: '/dashboard/seller/stores/new',
    store: (url: string) => `/dashboard/seller/stores/${url}`,
  },
};
